# Generated by Django 6.1 on 2026-09-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificaterequest_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='full_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
