# Generated by Django 6.1 on 2026-09-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_resident_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='certificaterequest',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_verification', 'Pending Verification'), ('paid', 'Paid')], default='unpaid', max_length=25),
        ),
    ]
