# Generated by Django 6.1 on 2026-10-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_certificaterequest_financing_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ready_for_pickup', 'Ready for Pickup'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
